[package]
name = "layout"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../math" }
log = "0.4"
console_log = { version = "0.2.0" }

[dev-dependencies]
test_util = { path = "../test_util" }